# duperscooper GUI Configuration
# This is the default configuration file.
# Your user configuration is stored in:
#   Linux/macOS: ~/.config/duperscooper/duperscooper-gui-options.toml
#   Windows: %APPDATA%\duperscooper\duperscooper-gui-options.toml

[colors.group_header]
# Colors for duplicate group headers in the results tree
background = "#f5f5f5"  # Light grey background
foreground = "#333333"  # Dark grey text

[colors.best_quality]
# Color for the best quality file/album (marked to keep)
color = "#2e7d32"  # Green

[colors.similarity]
# Colors for similarity percentages (match quality indicators)
very_high = "#1b5e20"  # Dark green - ≥99% similarity
high = "#388e3c"       # Green - ≥97% similarity
medium = "#f57c00"     # Orange - ≥95% similarity
low = "#c62828"        # Red - <95% similarity

# Thresholds for similarity color ranges (percentages)
threshold_very_high = 99.0
threshold_high = 97.0
threshold_medium = 95.0

[scan]
# Default scan options
default_mode = "album"  # "album" or "track"
algorithm = "perceptual"  # "perceptual" or "exact"
similarity_threshold = 98.0
workers = 8  # Number of parallel worker threads

[ui]
# UI preferences
window_width = 1000
window_height = 700
auto_expand_groups = true  # Automatically expand duplicate groups in results
